### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mateus224** [cyoon1729/RLcycle#1]
Hi, 
Do you can add some documentation to your code? Or a HowTo? I was running your code but  dont see that you save the learned model right? Because i would like to test it.

**Comment by cyoon1729** [comment]
Hi, apologies for the late reply. I haven't been able to spend time in this due personal issues.
I have made some rather huge changes to this repository, now merged to master. 
I plan to add a thorough documentation as well.
Thanks.
