### ISSUE TITLE
A2C save next_state to trajectory object

### ISSUE THREAD

**Issue by koryakinp** [cyoon1729/RLcycle#3]
https://github.com/cyoon1729/Reinforcement-learning/blob/d157d0d86c37734be4b430b7d311eb9bb0379d93/Policy-Gradient-Methods/a2c/a2c_test.py#L25

No need to save next_state, you never use it.

**Comment by cyoon1729** [comment]
Indeed. Sorry for the late replay - I haven't been able to spend time. However, I've addressed those changes in the recent refactoring, now merged to the master branch.
