### ISSUE TITLE
Agent initialize only synchronous Critic?

### ISSUE THREAD

**Issue by skywalker0803r** [cyoon1729/RLcycle#4]
# Copy critic target parameters
        for target_param, param in zip(self.critic_target.parameters(), self.critic.parameters()):
            target_param.data.copy_(param.data)

Actor need to sync?

**Comment by cyoon1729** [comment]
Sorry for the late replay - I haven't been able to spend time.  I've addressed those changes in the recent refactoring, now merged to the master branch.
